//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class thoi_khoa_bieu_sinh_vienEntities : DbContext
    {
        public thoi_khoa_bieu_sinh_vienEntities()
            : base("name=thoi_khoa_bieu_sinh_vienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<giang_vien> giang_vien { get; set; }
        public virtual DbSet<giang_vien_lop_hoc_phan> giang_vien_lop_hoc_phan { get; set; }
        public virtual DbSet<lich_hoc> lich_hoc { get; set; }
        public virtual DbSet<lop_hoc_phan> lop_hoc_phan { get; set; }
        public virtual DbSet<phan_quyen> phan_quyen { get; set; }
        public virtual DbSet<sinh_vien> sinh_vien { get; set; }
        public virtual DbSet<sinh_vien_lop_hoc_phan> sinh_vien_lop_hoc_phan { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tuan_hoc> tuan_hoc { get; set; }
    }
}
