//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinh_vien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sinh_vien()
        {
            this.sinh_vien_lop_hoc_phan = new HashSet<sinh_vien_lop_hoc_phan>();
        }
    
        public string sv_ma_sv { get; set; }
        public string sv_ho_dem { get; set; }
        public string sv_ten { get; set; }
        public byte sv_gioi_tinh { get; set; }
        public System.DateTime sv_ngay_sinh { get; set; }
        public string sv_ghi_chu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sinh_vien_lop_hoc_phan> sinh_vien_lop_hoc_phan { get; set; }
    }
}
