//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinh_vien_lop_hoc_phan
    {
        public string svlhp_id { get; set; }
        public string sv_ma_sv { get; set; }
        public string lhp_key_id { get; set; }
        public Nullable<byte> svlhp_nhom { get; set; }
    
        public virtual lop_hoc_phan lop_hoc_phan { get; set; }
        public virtual sinh_vien sinh_vien { get; set; }
    }
}
